### ISSUE TITLE
Plugin does not range beacons on iOS

### ISSUE THREAD

**Issue by EricHier** [ObjectivityLtd/beacon_monitoring#10]
Hi there! I've got the problem that the plugin does not range beacons within my application. These are the important parts of the code: 

AppDelegate.swift
```Swift

import UIKit
import Flutter
import CoreLocation
import beacon_monitoring

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    
    setupAppDelegateRegistry()
    setupBeaconMonitoringPluginCallback()
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  static func registerPlugins(with registry: FlutterPluginRegistry) {
      GeneratedPluginRegistrant.register(with: registry)
  }

  private func setupAppDelegateRegistry() {
      AppDelegate.registerPlugins(with: self)
  }
  private func setupBeaconMonitoringPluginCallback() {
      BeaconMonitoringPlugin.setPluginRegistrantCallback { registry in
          AppDelegate.registerPlugins(with: registry)
      }
  }
}

```

Within Flutter, I just do the following: 

```Dart

// ... permissions and stuff ...

await registerAllBeacons([RegionIBeacon(identifier: r.uuid, proximityUUID: r.uuid)]);

ranging().listen((event) {
  event.beacons.forEach((region) {
    print(region);
  });
});

```

The callback method is not called when I am close to the beacon. It is working fine on Android though. 

I am sure that the location permission has been granted correctly with precise location. No errors are thrown. The UUID is a valid UUID that is working fine within another iOS application. 

What can be the problem? How can I continue debugging? 

Thanks a lot for your help! :)

**Comment by MadDaelim** [comment]
HI,

There is indeed something not working on iOS, we are investigating this and probably a fix will be shipped with the null safety migration.

**Comment by EricHier** [comment]
@MadDaelim Thank you for your answer! Does a previous version work properly? I highly appreciate your help! :)

**Comment by MadDaelim** [comment]
@EricHier I don't know if the previous version works but we have a fix, if you wont to check it out you can change in pubspec.yaml your beacon_monitoring dependency to

    beacon_monitoring:
        git:
          url: git://github.com/ObjectivityLtd/beacon_monitoring
          ref: bugfix/10
          path: beacon_monitoring

and everything should work. Shortly I will release version 2.0.0 of the plugin with a fix for this bug. I will preserve the "bugfix/10" branch until the release.

**Comment by EricHier** [comment]
Wow thank you so much! 😇 I will give it a try. Thank you for your help.

**Comment by MadDaelim** [comment]
@EricHier a new version of lib has been released with the bug fixed. Thank you for contacting us.

**Comment by EricHier** [comment]
I've tried it out yesterday and it does not seem to work. Could you please reopen the issue? Once after letting the app run for over one minute, beacons were ranged on one device. Using a different device, there was no way to get it running. Is there a possibility to create debug logs to understand the issue?
