### ISSUE TITLE
Failed to build on iOS, No such module 'beacon_monitoring'

### ISSUE THREAD

**Issue by yossefEl** [ObjectivityLtd/beacon_monitoring#4]
Hi @MadDaelim   thank you for taking the time to develop this plugin!
I used the example app to test this on iOS but the build failed due to this error **No such module 'beacon_monitoring'**

**Comment by MadDaelim** [comment]
Hi @yossefEl could you give us more details like:
1. Past some stack trace?
2. What version of flutter and dart do you use?
4. On which iOS version you build the example?

**Comment by yossefEl** [comment]
> Hi @yossefEl could you give us more details like:
> 
> 1. Past some stack trace?
> 2. What version of flutter and dart do you use?
> 3. On which iOS version you build the example?

I'm sorry this wasn't an issue I forgot to add this to the pubspec.yaml
