### ISSUE TITLE
Is backgroundMonitoringCallback callback fires on iOS in terminated state?

### ISSUE THREAD

**Issue by andriy-gulak-ew** [ObjectivityLtd/beacon_monitoring#5]
I've set up `backgroundMonitoringCallback` in the app and have tested it on Android. It works fine in a terminated state because of running foreground service. 

But on iOS, it doesn't seem to be working. Well, at least it is not fired when a user terminates the app and leaves the beacon zone, for example. 

Can you please confirm or deny, that `backgroundMonitoringCallback` works on iOS?

**Comment by andriy-gulak-ew** [comment]
@MadDaelim can you please take a look and help me out with it?

**Comment by MadDaelim** [comment]
@andriy-gulak-ew Sorry for the delay I will try to verify that.
Could you share the code of the project? 
Can you reproduce it on example?

**Comment by MadDaelim** [comment]
Closed due to inactivity.
