### ISSUE TITLE
MissingPluginException: plugins.flutter.io/shared_preferences in backgroundMonitoringCallback on Android

### ISSUE THREAD

**Issue by andriy-gulak-ew** [ObjectivityLtd/beacon_monitoring#6]
When the app is terminated, the foreground service started background monitoring. In my `backgroundMonitoringCallback` I'm using a simple `shared_preferences` read operation. As a result, I'm getting the following:

```dart
E/flutter ( 3501): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 3501): 
```

`backgroundMonitoringCallback` configured according to the instructions.

Can you please help me with this? Looks like the plugin can't invoke any Dart code in `backgroundMonitoringCallback`.

**Comment by MadDaelim** [comment]
Closed due to inactivity.
