### ISSUE TITLE
How to change the app icon in Android foreground service?

### ISSUE THREAD

**Issue by andriy-gulak-ew** [ObjectivityLtd/beacon_monitoring#7]
Is there a way to change the app icon in Android foreground service?
![bm](https://user-images.githubusercontent.com/42183561/104161560-beec8380-53fb-11eb-98f1-d97dc6805130.png)

**Comment by MadDaelim** [comment]
Hi, you need to setup the ic_notification icon.
You can do it by adding the following folders in **android/app/src/main/res**:
* drawable-hdpi
* drawable-mdpi
* drawable-xhdpi
* drawable-xxhdpi
* drawable-xxxhdpi

and placing the appropriately sized **ic_notification.png** in them.

**Comment by MadDaelim** [comment]
Hi @andriy-gulak-ew, you need to set up the ic_notification icon.
You can do it by adding the following folders in **android/app/src/main/res**:
* drawable-hdpi
* drawable-mdpi
* drawable-xhdpi
* drawable-xxhdpi
* drawable-xxxhdpi
and placing the appropriately **sized ic_notification.png** in them.
