### ISSUE TITLE
What types of beacons does this plugin support?

### ISSUE THREAD

**Issue by andriy-gulak-ew** [ObjectivityLtd/beacon_monitoring#8]
Hi! First of all, thanks for your awesome plugin! 
@MadDaelim Can you please clarify what kind of beacon types does this plugin support?

For example, in the description, you described how to monitor iBeacons. What about other types like Eddystone, AltBeacon, and others. Thanks in advance!

**Comment by MadDaelim** [comment]
Hi @andriy-gulak-ew,

The library only supports iBeacons, but we use Eddystone beacons configured to mimic iBeacons. We have never worked with AltBeacons and others, so we can't say if the library will work with them.

Greetings.

**Comment by andriy-gulak-ew** [comment]
Ok, got it. Thank you for your answer @MadDaelim !
