### ISSUE TITLE
beacon_monitoring null-safety migration

### ISSUE THREAD

**Issue by andriy-gulak-ew** [ObjectivityLtd/beacon_monitoring#9]
Hi! Thanks for your great plugin. 

Do you plan to migrate the beacon_monitoring plugin to null-safety?

**Comment by MadDaelim** [comment]
Hi,

We are thinking about it, I will know by the end of the week when it will happen.

**Comment by MadDaelim** [comment]
Hi,

We will migrate the beacon_monitoring plugin to the null-safety by the end of the week.

**Comment by MadDaelim** [comment]
@andriy-gulak-ew the new version 2.0.0 is released and null-safety. Thank you for contacting us.
